### ISSUE TITLE
Abstract Chain should dispatch events based on constants

### ISSUE THREAD

**Issue by joaofernandes** [swiz/swiz-framework#1]
```
[Event( name="chainStarted",type="flash.events.Event" )]
[Event( name="chainStepComplete",type="flash.events.Event" )]
[Event( name="chainStepError",type="flash.events.Event" )]
[Event( name="chainComplete",type="flash.events.Event" )]
[Event( name="chainFailure",type="flash.events.Event" )]
```

All those events should correspond to a swizChainEvent constant so when listening to any of those we can use constants instead of literal strings.

like someAbstractChain.addEventListener(swizChainEvent.CHAIN_COMPLETE,someHandler)

**Comment by swiz** [comment]
Thanks Joao, this is currently on our todo list.

Ben

**Comment by brian428** [comment]
Joao, this has been completed. Thanks.
