### ISSUE TITLE
BeanFactory.isPotentialInjectionTarget interprets viewPackages incorrectly

### ISSUE THREAD

**Issue by Dretch** [swiz/swiz-framework#45]
The documentation (https://swizframework.jira.com/wiki/display/SWIZ/Updating+a+Swiz+0.6.4+application+to+Swiz+1.0) states that:

> the eventPackages and viewPackages now accept package paths in both the format myapp.events and myapp.events.*. Note that you still need to specify child packages separately even if you use the .\* syntax.

`BeanFactory.isPotentialInjectionTarget` does not work in accordance with this documentation - it returns true for child packages when it should return false. This means that views are processed by Swiz when they shouldn't be - in my case contributing to a performance issue.

I believe the bug is in this line of code: https://github.com/swiz/swiz-framework/blob/develop/src/org/swizframework/core/BeanFactory.as#L486

I can submit a pull request to fix this, if desired.

**Comment by Dretch** [comment]
I don't care about this any more, and I don't think anyone else does either!

**Comment by ROBERT-MCDOWELL** [comment]
submit your pull request at least! it can always be useful on a timeline.
