### ISSUE TITLE
IInitializingBean interface cannot be used by UIComponents

### ISSUE THREAD

**Issue by anacronw** [swiz/swiz-framework#8]
Not sure if this is still true of the 1.0 release, but I'm talking about the 0.6.4 beta release.

the interface specifies an "initialize" method which already exists in UIComponent.  Thus, none of my view code can actually use this interface.

I can do a workaround by hooking up a different bean that implements this interface and then injecting what I need.

**Comment by brian428** [comment]
This doesn't apply to 1.0, since it provides the [PostConstruct] metadata to define methods that run after the bean is created and dependencies/mediators are processed. Thanks for the feedback!
